name: pixabay_api
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  go_router: ^13.2.4
  http: ^1.2.1
  freezed_annotation:
  json_annotation:
  flutter_bloc: ^8.1.5
  storage_utility: ^1.0.0
  cached_network_image: ^3.3.1
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  build_runner:
  json_serializable:

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/noimage.jpg